services:
  wapp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=myapp_db
      - DB_USER=myapp_user
      - DB_PASSWORD=myapp_password
      - DB_ENGINE=django.db.backends.postgresql
    volumes:
      - ./storefront:/app
    depends_on:
      - db

  db:
    image: postgres:17.0
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
    volumes:
      - /var/lib/postgresql/data